### ISSUE TITLE
Error Dockerfile 

### ISSUE THREAD

**Issue by JamesRivers** [YannickOlivier/snp_exporter#1]
Dokerfile has erorr - need to remove `=` The syntax CMD = ["npm","run", "start"] is incorrect due to the presence of the = character, which is not valid in this context - should be 
```

FROM node:19
WORKDIR /usr/src/app
COPY package*.json .
RUN npm install
COPY . .
EXPOSE 8080
CMD ["npm", "run", "start"]

```

**Comment by YannickOlivier** [comment]
Thanks ! I'll fix it tonight.

**Comment by YannickOlivier** [comment]
Sorry for delay ! I fixed this problem with this commit https://github.com/YannickOlivier/snp_exporter/commit/6b32c94c61878861f90405e098f77e76315c25ee

**Comment by YannickOlivier** [comment]
Sorry for the delay ! I fixed this problem with this commit https://github.com/YannickOlivier/snp_exporter/commit/6b32c94c61878861f90405e098f77e76315c25ee
